language: julia
os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
  - julia: nightly
  - julia: 0.6
  - julia: 0.7

notifications:
  email: false

git:
  depth: 99999999

after_success:
  # push coverage results to Coveralls Pkg.test("CTPSS"; coverage = true);
  - julia -e 'using Pkg; cd(Pkg.dir("CTPSS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("CTPSS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
